# Generated by Django 5.1.7 on 2025-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busorder', '0002_busorderlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busorderlog',
            name='order_number',
        ),
        migrations.AddField(
            model_name='busorderlog',
            name='queue_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
