# Generated by Django 5.1.7 on 2025-04-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busorder', '0003_remove_busorderlog_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busorderlog',
            options={'permissions': [('can_access_busorder', 'Can access bus order feature'), ('can_access_all_logs', 'Can view all user logs')]},
        ),
    ]
