# Generated by Django 5.1.7 on 2025-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
