# Generated by Django 5.1.7 on 2025-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='공지로 등록'),
        ),
    ]
