# Generated by Django 5.1.7 on 2025-04-19 09:56

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_link',
            field=models.URLField(blank=True, default='', validators=[blog.validators.validate_place_link]),
            preserve_default=False,
        ),
    ]
