# Generated by Django 5.1.7 on 2025-04-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postlist_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostListPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_list_pics/')),
                ('post_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='blog.postlist')),
            ],
        ),
    ]
