# Generated by Django 5.1.7 on 2025-04-20 12:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postlistpics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlistpics',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post_list_pics/'),
        ),
    ]
