# Generated by Django 5.1.7 on 2025-04-20 13:00

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postlistpics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlistpics',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='post_list_pics/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='postlistpics',
            name='image',
            field=models.ImageField(upload_to='post_list_pics/original/'),
        ),
    ]
