# Generated by Django 5.1.7 on 2025-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postlistpics_thumbnail_alter_postlistpics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlistpics',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='post_list_pics/thumbnails/'),
        ),
    ]
