# Generated by Django 5.1.7 on 2025-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postlistpics_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlistpics',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
