# Generated by Django 5.1.7 on 2025-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postlistpics_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlistpics',
            name='metadata',
            field=models.JSONField(blank=True, help_text='EXIF 메타데이터(카메라, 렌즈, ISO 등)를 저장', null=True),
        ),
    ]
