# Generated by Django 5.1.7 on 2025-04-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_user_intro_user_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
